name: Notify Free Trial Expired every 12 hours

on:
  schedule:
    # Runs at 12-hour intervals
    # - cron: "0 */12 * * *"
    # Runs twice a day at 00:00 and 12:00 UTC
    - cron: "0 0,12 * * *"
  workflow_dispatch:

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call the Notify Free Trial Expired API
        run: |
          curl -X GET "https://5f29-101-0-63-251.ngrok-free.app/api/v0.1/notify/free-trial/expired?secret_key=SECRET_KEY"
