name: Notify Free Trial Expired every 12 hours

on:
  schedule:
    # Runs at 12-hour intervals
    # - cron: "0 */12 * * *"
    # Runs every minute
    - cron: "*/1 * * * *"

jobs:
  call-api:
    runs-on: ubuntu-latest
    steps:
      - name: Call the Notify Free Trial Expired API
        run: |
          curl -X GET "https://5f29-101-0-63-251.ngrok-free.app/notify/free-trial/expired?secret_key=SECRET_KEY"
